### ISSUE TITLE
最大化还原，全屏会有内容错乱的问题

### ISSUE THREAD

**Issue by Eviav** [NetDimension/WinForm-ModernUI#1]
以下代码加入一下 Anchor 或 Dock的控件位置会错乱
最大化，位置存在问题
![image](https://user-images.githubusercontent.com/13210002/44256257-345bc600-a23b-11e8-910c-76f8be0b701d.png)
![image](https://user-images.githubusercontent.com/13210002/44256277-40e01e80-a23b-11e8-9d59-97f0a65e4bdb.png)

环境：Win10 64 正常DPI

**最大化还原**

        public bool isMax = false;//记录是否最大化
        public void Max()
        {
            if (IsFullScreen)
            {
                FullScreen();
            }
            else
            {
                if (WindowState == FormWindowState.Maximized)
                {
                    isMax = false;
                    WindowState = FormWindowState.Normal;
                }
                else
                {
                    isMax = true;
                    WindowState = FormWindowState.Maximized;
                }
            }
        }

**全屏**

        public bool IsFullScreen = false;
        void FullScreen()
        {
            if (isMax)
            {
                isMax = false;
                this.FormBorderStyle = FormBorderStyle.None;
                this.WindowState = FormWindowState.Normal;
                this.WindowState = FormWindowState.Maximized;
                IsFullScreen = true;
            }
            else
            {
                if (this.WindowState == FormWindowState.Normal)
                {
                    this.FormBorderStyle = FormBorderStyle.None;
                    this.WindowState = FormWindowState.Maximized;
                    IsFullScreen = true;
                    //退出全屏
                }
                else
                {
                    IsFullScreen = false;
                    this.FormBorderStyle = FormBorderStyle.Sizable;
                    this.WindowState = FormWindowState.Normal;
                    //全屏
                }
            }
        }

**Comment by XuanchenLin** [comment]
@Haku-Men 抱歉，迟到的更新。
重新了整套逻辑，测试了下您说的问题，已经解决。
